### PR TITLE
fix gh actions

### PR DESCRIPTION
**Pull request by MartinSchobben**

### CODE REVIEW

**Comment by trel** [comment]
actionse -> actions

**Comment by trel** [comment]
is this working as intended?   i still see a failing action...

**Comment by MartinSchobben** [comment]
2 of the 50 or so what tests are failing on windows. I have no means right now to figure out why this ison windows alone. For macOS and Linux there are no problems are encountered.

Most importantly is that the website renders, so that documentation between the README, website and man pages is consistent.

**Comment by trel** [comment]
okay, happy to merge if you are ready.

**Pull request merged**
